Proyecto_FunCase_WEBLY/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Proyecto_FunCase_WEBLY.Models;

namespace Proyecto_FunCase_WEBLY.Controllers
{
    public class CarritoController : Controller
    {
        private FunCaseModelContext db = new FunCaseModelContext();

        [HttpPost]
        public JsonResult AgregaCarrito(int idProducto, int idImagen, int cantidad, string customImage)
        {

            string pathCustomImage = "";
            if(customImage != "null")
            {
                var image = Base64ToImage(customImage);
                string ruta = Path.Combine(Server.MapPath("~/Images/CustomUserPersonalization/" + idProducto));
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }
                var Timestamp = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliseconds();
                pathCustomImage =  String.Concat("/Images/CustomUserPersonalization/", idProducto, "/" , Timestamp.ToString() , ".png");
                image.Save(Path.Combine(ruta, Timestamp.ToString() + ".png" ));               
            }

            

            if(Session["carrito"] == null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                if (pathCustomImage.Equals(""))
                {
                    compras.Add(new CarritoItem(db.Productos.Find(idProducto), cantidad, db.Imagenes.Find(idImagen), null));
                }
                else
                {
                    compras.Add(new CarritoItem(db.Productos.Find(idProducto), cantidad, null, pathCustomImage));
                }
                
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];

                int indexExistente = getIndex(idProducto, idImagen, customImage);
                if(indexExistente == -1)
                {
                    if (pathCustomImage.Equals(""))
                    {
                        compras.Add(new CarritoItem(db.Productos.Find(idProducto), cantidad, db.Imagenes.Find(idImagen), null ));
                    }
                    else
                    {
                        compras.Add(new CarritoItem(db.Productos.Find(idProducto), cantidad, null, pathCustomImage));
                    }
                        
                }
                else
                {
                    compras[indexExistente].Cantidad += cantidad;
                }

                Session["carrito"] = compras;

            }
            return Json(new { response = true }, JsonRequestBehavior.AllowGet);
        }


        private Image Base64ToImage(string base64String)
        {
            // Convert base 64 string to byte[]
            string base64 = base64String.Split(',')[1];
            byte[] imageBytes = Convert.FromBase64String(base64);
            // Convert byte[] to Image
            using (var ms = new MemoryStream(imageBytes, 0, imageBytes.Length))
            {
                Image image = Image.FromStream(ms, true);
                return image;
            }
        }
        [HttpGet]
        public ActionResult AgregaCarrito()
        {
            return View();
        }

        public ActionResult Delete(int idProducto, int idImagen, string customImage)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
        
            compras.RemoveAt(getIndex(idProducto, idImagen, customImage));

            return View("AgregaCarrito");
        }

        [Authorize(Roles = "Cliente")]
        [HttpGet]
        public ActionResult ConfirmarPedido()
        {
            if(Session["carrito"] != null) {
                string currentUserId = User.Identity.GetUserId();
                Cliente cliente = db.Clientes.Single(c => c.UserId == currentUserId);
              
                ViewBag.DireccionID = new SelectList(db.Direcciones.Where(d => d.ClienteID == cliente.ClienteID && d.Estatus == true), "DireccionID", "NombreDireccion");
                ViewBag.MetodosPagoID = new SelectList(db.MetodosPagos, "MetodosPagoID", "Nombre");
                ViewBag.Producto = 1;
               
            } else
            {
                ViewBag.Productos = 0;
            }

            return View();
        }
        
        [HttpPost]
        public ActionResult FinalizarPedido(Pedido pedido)
        {
            if(Session["carrito"] != null)
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                if(compras != null && compras.Count > 0)
                {
                    try
                    {
                        string currentUserId = User.Identity.GetUserId();
                        double total = compras.Sum(x => x.Producto.Total * x.Cantidad);

                        pedido.ClienteID = db.Clientes.Where(c => c.UserId == currentUserId).FirstOrDefault().ClienteID;
                        pedido.EstatusPedido = "Generado";
                        pedido.EstatusPago = "Generado";
                        pedido.Total = total;

                        db.Pedidos.Add(pedido);

                        List<DetallesPedido> detalles = new List<DetallesPedido>();
                        foreach (var compra in compras)
                        {
                            DetallesPedido dp = new DetallesPedido
                            {
                                ProductoID = compra.Producto.ProductoID,
                                PrecioUnitario = compra.Producto.Total,
                                Cantidad = compra.Cantidad,
                                PedidoID = pedido.PedidoID
                            };
                            db.DetallePedidos.Add(dp);

                            Producto producto = db.Productos.Single(p => p.ProductoID == compra.Producto.ProductoID);
                            producto.Stock -= compra.Cantidad;
                            db.Entry(producto).State = System.Data.Entity.EntityState.Modified;

                            if (compra.customImage != null)
                            {
                                Funda_Diseno fd = new Funda_Diseno
                                {
                                    Imagen = compra.customImage,
                                    ValorNeto = compra.Producto.Total,
                                    DetallesPedidoID = dp.DetallesPedidoID
                                };
                                db.Funda_Disenos.Add(fd);
                            }
                            else
                            {
                                Funda_Diseno fd = new Funda_Diseno
                                {
                                    Imagen = compra.Imagen.Ruta,
                                    ValorNeto = compra.Producto.Total,
                                    DetallesPedidoID = dp.DetallesPedidoID
                                };
                                db.Funda_Disenos.Add(fd);

                                Imagen_Diseno id = new Imagen_Diseno
                                {
                                    ImagenID = compra.Imagen.ImagenID,
                                    Funda_DisenoID = fd.Funda_DisenoID
                                };

                                db.Imagen_Disenos.Add(id);
                            }
                            db.SaveChanges();
                        }
                    } catch (Exception e)
                    {
                        string currentUserId = User.Identity.GetUserId();
                        Cliente cliente = db.Clientes.Where(c => c.UserId == currentUserId).FirstOrDefault();
                        ViewBag.DireccionID = new SelectList(db.Direcciones.Where(d => d.ClienteID == cliente.ClienteID && d.Estatus == true), "DireccionID", "NombreDireccion");
                        ViewBag.MetodosPagoID = new SelectList(db.MetodosPagos, "MetodosPagoID", "Nombre");
                        ViewBag.Producto = 1;
                        ModelState.AddModelError("", e.Message);
                        ModelState.AddModelError("", "Debe tener una direcicón y un método de pago seleccionado");
                        return View("ConfirmarPedido");
                    }
                    
                }

                Session["carrito"] = null;
                return RedirectToAction("Index", "Pedidos");
            }

            return View();
        }

        private int getIndex(int idProducto, int idImagen, string customImage)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compras.Count; i++)
            {
                if (idImagen != 0 && idImagen != null)
                {
                    if (compras[i].Producto.ProductoID == idProducto && compras[i].Imagen.ImagenID == idImagen)
                        return i;
                }
                else
                {
                    if (compras[i].Producto.ProductoID == idProducto && compras[i].customImage == customImage)
                        return i;
                }
                
            }

            return -1;
        }


        [HttpGet]
        public JsonResult getStripeSecret(int idPedido)
        {
            try
            {
                PagosController pc = new PagosController();
                var pedido = db.Pedidos.Single(x => x.PedidoID == idPedido);
                double total = 0.0;
                foreach (DetallesPedido item in pedido.DetallesPedidos)
                {
                    total += item.PrecioUnitario * item.Cantidad;
                }                
                               

Proyecto_FunCase_WEBLY/Views/Carrito/AgregaCarrito.cshtml
@{
    ViewBag.Title = "Mi Carrito";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Carrito</h3>
                <p class="text-subtitle text-muted">Estos son los productos que has agregado.</p>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Imagen</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                double total = 0;
                            }
                            @if (Session["carrito"] != null)
                            {
                                foreach (var item in Session["carrito"] as List<Proyecto_FunCase_WEBLY.Models.CarritoItem>)
                                {
                                    total += item.calcularTotal();
                                    <tr>
                                        <td>@item.Producto.Nombre</td>
                                        <td>
                                            @if (item.Imagen != null)
                                            {
                                                <img class="img-responsive" src="@item.Imagen.Ruta" alt="Imagen" style="height: 150px;" />
                                            }
                                            else
                                            {
                                                <img class="img-responsive" src="@item.customImage" alt="Imagen" style="height: 150px;" />
                                            }

                                        </td>
                                        <td>@String.Format("{0:C}", item.Producto.Total)</td>
                                        <td>@item.Cantidad</td>
                                        <td>@String.Format("{0:C}", item.calcularTotal())</td>
                                        <td>@Html.ActionLink("Eliminar", "Delete", "Carrito", new { idProducto = item.Producto.ProductoID, idImagen = (item.Imagen != null) ? item.Imagen.ImagenID : 0, customImage = item.customImage }, null)</td>
                                    </tr>
                                }
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="4">Total</th>
                                <th>@String.Format("{0:C}", total)</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12" style="text-align: right;">
                @Html.ActionLink("Seguir Comprando", "Index", "Productos", null, new { @class = "btn btn-outline-info" })
                @Html.ActionLink("Confirmar Compra", "ConfirmarPedido", "Carrito", null, new { @class = "btn btn-outline-success" })
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Carrito/ConfirmarPedido.cshtml
@model Proyecto_FunCase_WEBLY.Models.Pedido
@{
    ViewBag.Title = "Confirmar Pedidio";
}

@if (ViewBag.Productos != 0)
{
    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Pedido</h3>
                    <p class="text-subtitle text-muted">Resumen del pedido</p>
                </div>
            </div>
        </div>
    </div>

    <div class="page-content">
        <section class="section">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Datos del Pedido</h4>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                @using (Html.BeginForm("FinalizarPedido", "Carrito", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="mb-3 row">
                                            @Html.LabelFor(model => model.MetodosPagoID, "Metodos de Pago", htmlAttributes: new { @class = "form-label col-lg-5 col-md-4 col-sm-4 col-form-label" })
                                            <div class="col-lg-7 col-md-8 col-sm-8">
                                                @Html.DropDownList("MetodosPagoID", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.MetodosPagoID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="mb-3 row">
                                            @Html.LabelFor(model => model.DireccionID, "Dirección de Envío", htmlAttributes: new { @class = "form-label col-lg-5 col-md-4 col-sm-4 col-form-label" })
                                            <div class="col-lg-7 col-md-8 col-sm-8">
                                                @Html.DropDownList("DireccionID", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.DireccionID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <a href="@Url.Action("Create","Direccion")" class="btn btn-outline-info">Registrar Dirección</a>
                                        <button type="submit" class="btn btn-outline-success">Pedir</button>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Productos Agregados</h4>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Nombre</th>
                                                <th>Imagen</th>
                                                <th>Precio</th>
                                                <th>Cantidad</th>
                                                <th>Total</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                double total = 0;
                                            }
                                            @if (Session["carrito"] != null)
                                            {
                                                foreach (var item in Session["carrito"] as List<Proyecto_FunCase_WEBLY.Models.CarritoItem>)
                                                {
                                                    total += item.calcularTotal();
                                                    <tr>
                                                        <td>@item.Producto.Nombre</td>
                                                        <td>
                                                            @if (item.Imagen != null)
                                                            {
                                                                <img class="img-responsive" src="@item.Imagen.Ruta" alt="Imagen" style="height: 150px;" />
                                                            }
                                                            else
                                                            {
                                                                <img class="img-responsive" src="@item.customImage" alt="Imagen" style="height: 150px;" />
                                                            }

                                                        </td>
                                                        <td>@String.Format("{0:C}", item.Producto.Total)</td>
                                                        <td>@item.Cantidad</td>
                                                        <td>@String.Format("{0:C}", item.calcularTotal())</td>
                                                        <td>@Html.ActionLink("Eliminar", "Delete", "Carrito", new { idProducto = item.Producto.ProductoID, idImagen = (item.Imagen != null) ? item.Imagen.ImagenID : 0, customImage = item.customImage }, null)</td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="4">Total</th>
                                                <th>@String.Format("{0:C}", total)</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
}
else
{
    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Carrito</h3>
                    <p class="text-subtitle text-muted">Estos son los productos que has agregado.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="page-content">
        <section class="section">
            <div class="row">
                <div class="col-12">
                    <p>Agregue productos para realizar una compra</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12" style="text-align: right;">
                    @Html.ActionLink("Comprar", "Index", "Productos", null, new { @class = "btn btn-outline-info" })
                </div>
            </div>
        </section>
    </div>

}

Proyecto_FunCase_WEBLY/Views/Carrito/FinalizarPedido.cshtml
@model Proyecto_FunCase_WEBLY.Models.Pedido
@{
    ViewBag.Title = "Finalizar Pedido";
}

<h2>Gracias por su compra, vuelva Pronto</h2>
<p>@Html.ActionLink("Continuar", "Index", "Home", null, null)</p>