Proyecto_FunCase_WEBLY/Controllers/ImagenesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Proyecto_FunCase_WEBLY.Models;

namespace Proyecto_FunCase_WEBLY.Controllers
{
    [Authorize(Roles = "Diseñador")]
    public class ImagenesController : Controller
    {
        // GET: Imagenes
        private FunCaseModelContext db = new FunCaseModelContext();
        
        public ActionResult Index()
        {

            try
            {
                string currentUserId = User.Identity.GetUserId();
                var user = db.Users.Find(currentUserId);
                var role = db.Roles.Where(x => x.Name == "Diseñador").FirstOrDefault();

                if (user.Roles.Where(x => x.RoleId == role.Id).FirstOrDefault() != null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var designer = db.Designers.Where(x => x.UserId == currentUserId).FirstOrDefault();

                return View(designer.Imagenes);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // GET: Imagenes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(db.Imagenes.FirstOrDefault(x => x.ImagenID == id));
        }

        // GET: Imagenes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Imagenes/Create
        [HttpPost]
        public ActionResult Create(Imagen imagen)
        {
            try
            {
                string currentUserId = User.Identity.GetUserId();
                var designerId = db.Designers.Where(x => x.UserId == currentUserId).FirstOrDefault().DesignerID;

                string ruta = Path.Combine(Server.MapPath("~/Images/disenador/" + designerId ));
                
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    if (hpf.ContentLength == 0)
                        continue;
                    string savedFileName = Path.Combine(ruta, Path.GetFileName(hpf.FileName));
                    hpf.SaveAs(savedFileName);
                    imagen.Ruta = String.Concat("/Images/disenador/", designerId.ToString(), "/", hpf.FileName);
                }

            
                imagen.DesignerID = designerId;

                db.Imagenes.Add(imagen);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Imagenes/Edit/5
        public ActionResult Edit(int? id)
        {
                     
            return View(db.Imagenes.FirstOrDefault(x => x.ImagenID == id));
        }

        // POST: Imagenes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Imagen imagen)
        {
            try
            {

                string currentUserId = User.Identity.GetUserId();
                var designerId = db.Designers.Where(x => x.UserId == currentUserId).FirstOrDefault().DesignerID;
                string ruta = Path.Combine(Server.MapPath("~/Images/disenador/" + designerId));
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    if (hpf.ContentLength == 0)
                        break;
                    string savedFileName = Path.Combine(ruta, Path.GetFileName(hpf.FileName));
                    hpf.SaveAs(savedFileName);
                    imagen.Ruta = String.Concat("/Images/disenador/", designerId.ToString(), "/", hpf.FileName);
                }

                imagen.DesignerID = designerId;
                db.Entry(imagen).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return View(imagen);
            }
            
        }

    }
}

Proyecto_FunCase_WEBLY/Views/Imagenes/Create.cshtml
@model Proyecto_FunCase_WEBLY.Models.Imagen

@{
    ViewBag.Title = "Crear";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Crear</h3>
                <p class="text-subtitle text-muted">Da a conocer tu nuevo diseño.</p>
            </div>
        </div>
    </div>
</div>

<section style="margin-top: 20px;">
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Create", "Imagenes", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary("", new { @class = "text-error" })

                                <div class="row">
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.NombreImagen)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.NombreImagen, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.NombreImagen, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Ruta)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.TextBoxFor(model => model.Ruta, new { type = "file", @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Ruta, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="card-footer d-flex justify-content-between">
                                        <div class="col-12 d-flex justify-content-end">
                                            @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                            <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto_FunCase_WEBLY/Views/Imagenes/Details.cshtml
@model Proyecto_FunCase_WEBLY.Models.Imagen

@{
    ViewBag.Title = "Detalles";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Detalles</h3>
                <p class="text-subtitle text-muted">Visualiza los datos de tu diseño.</p>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row match-height">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Diseño: @Model.NombreImagen</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form>
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Estatus</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            @Html.DisplayFor(model => model.Estatus)
                                        </div>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div class="col-12 d-flex justify-content-end">
                            @Html.ActionLink("Editar Diseño", "Edit", new { id = Model.ImagenID }, new { @class = "btn btn-info rounded-pill me-1 mb-1" })
                            @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Mi diseño</h4>
                    </div>

                    <div class="card-content">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12" style="text-align: center;">
                                    <img src="@Model.Ruta" alt="Imagen del Modelo" style="height: 300px;" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Imagenes/Edit.cshtml
@model Proyecto_FunCase_WEBLY.Models.Imagen

@{
    ViewBag.Title = "Editar";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Editar</h3>
                <p class="text-subtitle text-muted">Cambiar mi diseño.</p>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Ingrese los datos</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Edit", "Imagenes", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.ImagenID)
                                <div class="row">
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.NombreImagen)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.NombreImagen, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.NombreImagen, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-check-input" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Ruta)
                                        <p class="form-text">Eliga un archivo solo si desea cambiar la imagen</p>
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        <input type="file" id="File" name="File" class="form-control" />
                                        @Html.HiddenFor(model => model.Ruta)
                                        @Html.ValidationMessageFor(model => model.Ruta, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-12 d-flex justify-content-end">
                                        @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                        <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Diseño</h4>
                </div>

                <div class="card-content">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12" style="text-align: center;">
                                <img src="@Model.Ruta" alt="Imagen del Modelo" style="height: 300px;" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto_FunCase_WEBLY/Views/Imagenes/Index.cshtml
@model IEnumerable<Proyecto_FunCase_WEBLY.Models.Imagen>

@{
    ViewBag.Title = "Index";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Mis imágenes</h3>
                <p class="text-subtitle text-muted">Aquí se presentan tu ideas.</p>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header" style="text-align: right;">
                        <p class="float-start float-lg-end float-md-end float-sm-end">
                            @Html.ActionLink("Crear nuevo registro", "Create", null, new { @class = "btn btn-outline-success" })
                        </p>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-lg">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NombreImagen)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Ruta)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Estatus)
                                        </th>
                                        <th>
                                            Número de pedidos
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.NombreImagen)
                                            </td>
                                            <td>
                                                <img class="img-responsive" src="@item.Ruta" height="300" />
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Estatus)
                                            </td>
                                            <td>
                                                @item.Imagen_Disenos.Count()
                                            </td>
                                            <td>
                                                @Html.ActionLink("Editar", "Edit", new { id = item.ImagenID }, new { @class = "btn btn-primary rounded-pill" })
                                                @Html.ActionLink("Detalles", "Details", new { id = item.ImagenID }, new { @class = "btn btn-info rounded-pill" })

                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>