Proyecto_FunCase_WEBLY/Controllers/ProveedoresController.cs
using Proyecto_FunCase_WEBLY.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_FunCase_WEBLY.Controllers
{
    [Authorize(Roles = "Empleado")]
    public class ProveedoresController : Controller
    {
        FunCaseModelContext db = new FunCaseModelContext();
        // GET: Proveedores
        public ActionResult Index()
        {
            return View(db.Proveedores.ToList());
        }

        // GET: Proveedores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedor proveedor = db.Proveedores.Find(id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }
            
            return View(proveedor);
        }

        // GET: Proveedores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        [HttpPost]
        public ActionResult Create(Proveedor proveedor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Proveedores.Add(proveedor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(proveedor);
            }
            catch
            {
                return View(proveedor);
            }
        }

        // GET: Proveedores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedor proveedor = db.Proveedores.Find(id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }
            return View(proveedor);
        }

        // POST: Proveedores/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Proveedor proveedor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(proveedor).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(proveedor);
            }
            catch
            {
                return View();
            }
        }

        // GET: Proveedores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedor proveedor = db.Proveedores.Find(id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }
            return View(proveedor);
        }

        // POST: Proveedores/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                Proveedor proveedor = db.Proveedores.Find(id);
                proveedor.Estatus = false;
                db.Entry(proveedor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto_FunCase_WEBLY/Views/Proveedores/Create.cshtml
@model Proyecto_FunCase_WEBLY.Models.Proveedor

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Crear</h3>
                <p class="text-subtitle text-muted">Dar de alta un nuevo Proveedor.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Crear</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Ingrese los datos</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Create", "Proveedores", FormMethod.Post, new { @class = "form form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary("", new { @class = "text-error" })

                                <div class="row">
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Nombre)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Apellido1)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Apellido1, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Apellido1, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Apellido2)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Apellido2, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Apellido2, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Email)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Telefono)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Empresa)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="card-footer d-flex justify-content-between">
                                        <div class="col-12 d-flex justify-content-end">
                                            <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                            @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Proyecto_FunCase_WEBLY/Views/Proveedores/Delete.cshtml
@model Proyecto_FunCase_WEBLY.Models.Proveedor

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Eliminar</h3>
                <p class="text-subtitle text-muted">¿Esta seguro de eliminar este Proveedor?</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Eliminar</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row match-height">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Proveedor: @Model.ProveedorID</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form>
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Nombre</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Nombre" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Primer Apellido</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Apellido1" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Segundo Apellido</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Apellido2" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Email" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Teléfono</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Telefono" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Empresa</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Empresa" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Estatus</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            @Html.DisplayFor(model => model.Estatus)
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div class="col-12 d-flex justify-content-end">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger rounded-pill me-1 mb-1">Eliminar</button>
                                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Proveedores/Details.cshtml
@model Proyecto_FunCase_WEBLY.Models.Proveedor

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Detalles";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Detalles</h3>
                <p class="text-subtitle text-muted">Visualiza los datos del proveedor.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Detalles</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row match-height">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Proveedor: @Model.ProveedorID</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form>
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Nombre</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Nombre" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Primer Apellido</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Apellido1" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Segundo Apellido</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Apellido2" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Email" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Teléfono</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Telefono" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Empresa</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Empresa" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Estatus</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            @Html.DisplayFor(model => model.Estatus)
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div class="col-12 d-flex justify-content-end">
                            @Html.ActionLink("Editar Proveedor", "Edit", new { id = Model.ProveedorID }, new { @class = "btn btn-info rounded-pill me-1 mb-1" })
                            @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Proveedores/Edit.cshtml
@model Proyecto_FunCase_WEBLY.Models.Proveedor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Editar</h3>
                <p class="text-subtitle text-muted">Cambiar los datos del proveedor.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Editar</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>


<section>
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Ingrese los datos</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Edit", "Proveedores", FormMethod.Post, new { @class = "form form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.ProveedorID)
                                <div class="row">
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Nombre)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "form-text invalid-feedback" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Apellido1)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Apellido1, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Apellido1, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Apellido2)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Apellido2, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Apellido2, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Email)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Telefono)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Empresa)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-check-input" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="col-sm-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                        @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>