Proyecto_FunCase_WEBLY/Models/Marca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto_FunCase_WEBLY.Models
{
    public class Marca
    {
        public int MarcaID { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Display(Name = "Estatus de la Marca")]
        public bool Estatus { get; set; }

        public Marca()
        {
            this.Modelos = new HashSet<Modelo>();
        }

        public virtual ICollection<Modelo> Modelos { get; set; }

    }
}

Proyecto_FunCase_WEBLY/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using Proyecto_FunCase_WEBLY.Models;

namespace Proyecto_FunCase_WEBLY.Views.Home
{
    [Authorize(Roles = "Empleado")]
    public class MarcasController : Controller
    {
        private FunCaseModelContext db = new FunCaseModelContext();

        // GET: Marcas
        public ActionResult Index()
        {
            return View(db.Marcas.ToList());
        }

        // GET: Marcas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marcas.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // GET: Marcas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marcas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Marcas.Add(marca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: Marcas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marcas.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marcas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(marca);
        }

        // GET: Marcas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marcas.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Marca marca = db.Marcas.Find(id);
            marca.Estatus = false;
            db.Entry(marca).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_FunCase_WEBLY/Views/Marcas/Create.cshtml
@model Proyecto_FunCase_WEBLY.Models.Marca

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Crear</h3>
                <p class="text-subtitle text-muted">Dar de alta una nueva Marca.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Marcas")">Marcas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Crear</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Ingrese los datos</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Create", "Marcas", FormMethod.Post, new { @class = "form form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary("", new { @class = "text-error" })

                                <div class="row">
                                    <div class="col-12 form-group">
                                        <h6 class="card-subtitle">Datos personales</h6>
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Nombre)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="card-footer d-flex justify-content-between">
                                        <div class="col-12 d-flex justify-content-end">
                                            <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                            @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto_FunCase_WEBLY/Views/Marcas/Delete.cshtml
@model Proyecto_FunCase_WEBLY.Models.Marca

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Eliminar</h3>
                <p class="text-subtitle text-muted">¿Esta seguro de eliminar esta Marca?</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Marcas")">Marcas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Eliminar</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row match-height">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Marca: @Model.MarcaID</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form>
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Nombre</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Nombre" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Estatus</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            @Html.DisplayFor(model => model.Estatus)
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div class="col-12 d-flex justify-content-end">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger rounded-pill me-1 mb-1">Eliminar</button>
                                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Marcas/Details.cshtml
@model Proyecto_FunCase_WEBLY.Models.Marca

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Detalles</h3>
                <p class="text-subtitle text-muted">Visualiza los datos de la marca.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Marcas")">Marcas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Detalles</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <section class="section">
        <div class="row match-height">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Marca: @Model.MarcaID</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form>
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Nombre</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            <input type="text" value="@Model.Nombre" class="form-control" readonly />
                                        </div>
                                        <div class="col-sm-4 col-md-5 col-lg-6">
                                            <label>Estatus</label>
                                        </div>
                                        <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                            @Html.DisplayFor(model => model.Estatus)
                                        </div>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div class="col-12 d-flex justify-content-end">
                            @Html.ActionLink("Editar Marca", "Edit", new { id = Model.MarcaID }, new { @class = "btn btn-info rounded-pill me-1 mb-1" })
                            @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Proyecto_FunCase_WEBLY/Views/Marcas/Edit.cshtml
@model Proyecto_FunCase_WEBLY.Models.Marca

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Editar</h3>
                <p class="text-subtitle text-muted">Cambiar los datos de la marca.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Marcas")">Marcas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Editar</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>


<section>
    <div class="row match-height">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Ingrese los datos</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">

                        @using (Html.BeginForm("Edit", "Marcas", FormMethod.Post, new { @class = "form form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-body">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.MarcaID)
                                <div class="row">
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Nombre)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "form-text invalid-feedback" })
                                    </div>
                                    <div class="col-sm-4 col-md-5 col-lg-6">
                                        @Html.LabelFor(model => model.Estatus)
                                    </div>
                                    <div class="col-sm-8 col-md-7 col-lg-6 form-group">
                                        @Html.EditorFor(model => model.Estatus, new { @class = "form-check-input" })
                                        @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "form-text text-danger" })
                                    </div>
                                    <div class="col-sm-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary rounded-pill me-1 mb-1">Guardar</button>
                                        @Html.ActionLink("Volver al Listado", "Index", null, new { @class = "btn btn-light-secondary rounded-pill me-1 mb-1" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto_FunCase_WEBLY/Views/Marcas/Index.cshtml
@model IEnumerable<Proyecto_FunCase_WEBLY.Models.Marca>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Marcas</h3>
                <p class="text-subtitle text-muted">Lista de marcas de dispositivos móviles agregados.</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end float-md-end float-sm-end">
                    <ol class="breadcrumb breadcrumb-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("IndexAdmin", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Marcas</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>


<div class="page-content">
    <section class="section">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6">
                                <h4 class="card-title">Materiales registrados</h4>
                            </div>
                            <div class="col-6">
                                <p class="float-start float-lg-end float-md-end float-sm-end">
                                    @Html.ActionLink("Crear nuevo registro", "Create", "", new { @class = "btn btn-outline-success" })
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-lg table-hover">
                                    <tr class="table-success">
                                        <th>
                                            @Html.DisplayNameFor(model => model.Nombre)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Estatus)
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Nombre)
                                            </td>
                                            <th>
                                                @Html.DisplayFor(modelItem => item.Estatus)
                                            </th>
                                            <td>
                                                <div class="float-start float-lg-end float-md-end float-sm-end">
                                                    @Html.ActionLink("Editar", "Edit", new { id = item.MarcaID }, new { @class = "btn btn-primary rounded-pill" })
                                                    @Html.ActionLink("Detalles", "Details", new { id = item.MarcaID }, new { @class = "btn btn-info rounded-pill" })
                                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.MarcaID }, new { @class = "btn btn-danger rounded-pill" })
                                                </div>
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>